export type Locale = 'zh' | 'en' | 'zhdy';

export const COPY = {
  zh: {
    painTitle: '助手出不去这台电脑。',
    home: '家里',
    office: '公司',
    colo: '机房',
    online: '在线',
    offline: '不在对话里',
    official: 'THIS MACHINE',
    connecting: '助手只能动这台…',
    disconnected: '出不去这台电脑',
    stamp: '出不去这台电脑',
    loopNames: 'Codex · Claude Code · Grok',
    thisMachine: '这台电脑',
    productTitle: '一个工具。所有电脑。随时随地。',
    sameCmd: '同一条命令 · 三台都收到',
    principleTitle: '工具 → 云上 → 每一台电脑',
    toolKicker: 'TOOL',
    toolTitle: 'Codex / Claude / Grok',
    toolSub: '任意通用助手 · 导入工具',
    hubKicker: 'SERVER',
    hubTitle: 'fleet.ginfo.cc',
    hubSub: '云上 · 只出网',
    winSub: 'Agent 自己连出去',
    linuxSub: 'Agent 自己连出去',
    macSub: 'Agent 自己连出去',
    principleCaption: '设备只出网 · 不开端口 · 架构不限',
    collabTitle: '换一个助手。舰队还在。',
    mcpImported: '工具已导入',
    sameCreds: '  · 同一套 URL + 令牌',
    officialCh: '官方远程',
    officialDown: '只能盯一台',
    officialSub: '换设备就接不上。',
    fleetOn: '任意助手',
    fleetSub: '导入工具，多台都在。不限系统。',
    setupTitle: '四样东西。然后所有电脑都在。',
    key1t: '域名 URL',
    key1s: 'https://fleet.ginfo.cc',
    key2t: 'Hub 令牌',
    key2s: '设置页生成 flt_…',
    key3t: '每台电脑的 Agent',
    key3s: 'Windows / Linux / macOS',
    key4t: '导入 Tool',
    key4s: '任意通用助手',
    cloudTitle: '本地只是命令行。云端才是产品。',
    localKicker: 'LOCAL　本机中枢',
    localTitle: '最多是个命令行',
    localBody: '中枢跑在本机，发挥不出多端互联。别的系统加不进来，也做不到随时随地。',
    cloudKicker: 'CLOUD　fleet.ginfo.cc',
    cloudHead: '这才是产品',
    cloudBody: '把 Server 放到云上。Windows、Linux、Mac 自己出网。一个工具够到每一台。',
    ctaKicker: '先来这里体验',
    ctaUrl: 'fleet.ginfo.cc',
    ctaSteps: '登录 · 生成令牌 · 装 Agent · 导入工具',
    ctaLine: '一个工具，你的所有电脑。',
    machines: [
      {place: '家里', os: 'Windows', cmd: '家里 Windows'},
      {place: '公司', os: 'macOS', cmd: '公司 macOS'},
      {place: '机房', os: 'Linux', cmd: '机房 Linux'},
    ],
  },
  // Douyin-safe: show fleet.ginfo.cc, never say “go visit / log in / try it”.
  zhdy: {
    painTitle: '助手出不去这台电脑。',
    home: '家里',
    office: '公司',
    colo: '机房',
    online: '在线',
    offline: '不在对话里',
    official: 'THIS MACHINE',
    connecting: '助手只能动这台…',
    disconnected: '出不去这台电脑',
    stamp: '出不去这台电脑',
    loopNames: 'Codex · Claude Code · Grok',
    thisMachine: '这台电脑',
    productTitle: '一个工具。所有电脑。随时随地。',
    sameCmd: '同一条命令 · 三台都收到',
    principleTitle: '工具 → 云上 → 每一台电脑',
    toolKicker: 'TOOL',
    toolTitle: 'Codex / Claude / Grok',
    toolSub: '任意通用助手 · 导入工具',
    hubKicker: 'SERVER',
    hubTitle: 'fleet.ginfo.cc',
    hubSub: '云上 · 只出网',
    winSub: '自己向外连出去',
    linuxSub: '自己向外连出去',
    macSub: '自己向外连出去',
    principleCaption: '设备只出网 · 不开端口 · 架构不限',
    collabTitle: '换一个助手。舰队还在。',
    mcpImported: '工具已导入',
    sameCreds: '  · 同一套接入点 + 令牌',
    officialCh: '官方远程',
    officialDown: '只能盯一台',
    officialSub: '换设备就接不上。',
    fleetOn: '任意助手',
    fleetSub: '导入工具，多台都在。不限系统。',
    setupTitle: '四样东西。然后所有电脑都在。',
    key1t: '中枢地址',
    key1s: 'fleet.ginfo.cc',
    key2t: 'Hub 令牌',
    key2s: '设置页生成 flt_…',
    key3t: '每台电脑的程序',
    key3s: 'Windows / Linux / macOS',
    key4t: '导入工具',
    key4s: '任意通用助手',
    cloudTitle: '本地只是命令行。云端才是产品。',
    localKicker: 'LOCAL　本机中枢',
    localTitle: '最多是个命令行',
    localBody: '中枢跑在本机，发挥不出多端互联。别的系统加不进来，也做不到随时随地。',
    cloudKicker: 'CLOUD',
    cloudHead: '这才是产品',
    cloudBody: '把服务放到云上。Windows、Linux、Mac 自己出网。一个工具够到每一台。',
    ctaKicker: '多端互联',
    ctaUrl: 'fleet.ginfo.cc',
    ctaSteps: '设备只出网 · 不开端口 · 架构不限',
    ctaLine: '一个工具。所有电脑。',
    machines: [
      {place: '家里', os: 'Windows', cmd: '家里 Windows'},
      {place: '公司', os: 'macOS', cmd: '公司 macOS'},
      {place: '机房', os: 'Linux', cmd: '机房 Linux'},
    ],
  },
  en: {
    painTitle: 'It cannot leave this computer.',
    home: 'HOME',
    office: 'WORK',
    colo: 'COLO',
    online: 'Online',
    offline: 'Not in the chat',
    official: 'THIS MACHINE',
    connecting: 'Only this computer…',
    disconnected: 'Cannot leave this computer',
    stamp: 'Cannot leave this computer',
    loopNames: 'Codex · Claude Code · Grok',
    thisMachine: 'This laptop',
    productTitle: 'One tool. Every computer. Anywhere.',
    sameCmd: 'One command · all three receive it',
    principleTitle: 'Tool → cloud → every PC',
    toolKicker: 'TOOL',
    toolTitle: 'Codex / Claude / Grok',
    toolSub: 'Any general agent · import the tool',
    hubKicker: 'SERVER',
    hubTitle: 'fleet.ginfo.cc',
    hubSub: 'Cloud · outbound only',
    winSub: 'Agent dials out',
    linuxSub: 'Agent dials out',
    macSub: 'Agent dials out',
    principleCaption: 'Devices only dial out · no inbound ports · any arch',
    collabTitle: 'Switch the agent. The fleet stays.',
    mcpImported: 'Tool loaded',
    sameCreds: '  · same URL + token',
    officialCh: 'OFFICIAL REMOTE',
    officialDown: 'One box only',
    officialSub: 'Switch the device and it dies.',
    fleetOn: 'Any agent',
    fleetSub: 'Load the tool. Every computer stays.',
    setupTitle: 'Four values. Then every PC is reachable.',
    key1t: 'Domain URL',
    key1s: 'https://fleet.ginfo.cc',
    key2t: 'Hub token',
    key2s: 'Mint flt_… in Settings',
    key3t: 'Agent on each PC',
    key3s: 'Windows / Linux / macOS',
    key4t: 'Import the tool',
    key4s: 'GPT · Grok · Claude · Codex',
    cloudTitle: 'Local is a CLI. Cloud is the product.',
    localKicker: 'LOCAL  your own machine',
    localTitle: 'At most a CLI',
    localBody: 'A hub on localhost cannot run a fleet. Other OS cannot join. Nowhere near “from anywhere.”',
    cloudKicker: 'CLOUD  fleet.ginfo.cc',
    cloudHead: 'This is the product',
    cloudBody: 'Put the server in the cloud. Windows, Linux, Mac dial out. One tool reaches every PC.',
    ctaKicker: 'Start here',
    ctaUrl: 'fleet.ginfo.cc',
    ctaSteps: 'One tool · every computer · any agent',
    ctaLine: 'Like local Codex. Across all your machines.',
    machines: [
      {place: 'HOME', os: 'Windows', cmd: 'Home Windows'},
      {place: 'WORK', os: 'macOS', cmd: 'Work macOS'},
      {place: 'COLO', os: 'Linux', cmd: 'Colo Linux'},
    ],
  },
} as const;
