export type Locale = 'zh' | 'en';

export const COPY = {
  zh: {
    painTitle: '人对上了。电脑对不上。',
    home: '家里',
    office: '公司',
    colo: '机房',
    online: '在线',
    offline: '已断开',
    official: 'OFFICIAL REMOTE',
    connecting: '正在连接你的电脑…',
    disconnected: '连接已断开',
    stamp: '官方通道 · 又断了',
    productTitle: '一个工具。所有电脑。随时随地。',
    sameCmd: '同一条命令 · 三台都收到',
    principleTitle: '工具 → 云端中枢 → 每一台电脑',
    toolKicker: 'TOOL',
    toolTitle: 'Cursor / Claude',
    toolSub: '任意交互式 AI · MCP',
    hubKicker: 'SERVER',
    hubTitle: 'fleet.ginfo.cc',
    hubSub: '云端中枢 · 只出网',
    winSub: 'Agent 自己连出去',
    linuxSub: 'Agent 自己连出去',
    macSub: 'Agent 自己连出去',
    principleCaption: '设备只出网 · 不开端口 · 架构不限',
    collabTitle: '换一个助手。舰队还在。',
    mcpImported: 'MCP 已导入',
    sameCreds: '  · 同一套 URL + 令牌',
    officialCh: '官方通道',
    officialDown: '断开',
    officialSub: '上下文没了。机器不在对话里。',
    fleetOn: '还在',
    fleetSub: '认中枢，不认某一家客户端。',
    setupTitle: '四样东西。然后所有电脑都在。',
    key1t: '域名 URL',
    key1s: 'https://fleet.ginfo.cc',
    key2t: 'Hub 令牌',
    key2s: '设置页生成 flt_…',
    key3t: '每台电脑的 Agent',
    key3s: 'Windows / Linux / macOS',
    key4t: '导入 Tool',
    key4s: '任意交互式 AI · MCP',
    cloudTitle: '本地只是命令行。云端才是产品。',
    localKicker: 'LOCAL　本机中枢',
    localTitle: '最多是个命令行',
    localBody: '中枢跑在本机，发挥不出多端互联。别的系统加不进来，也做不到随时随地。',
    cloudKicker: 'CLOUD　fleet.ginfo.cc',
    cloudHead: '这才是产品',
    cloudBody: '把 Server 放到云上。Windows、Linux、Mac 自己出网。一个工具够到每一台。',
    ctaKicker: '先来这里体验',
    ctaUrl: 'fleet.ginfo.cc',
    ctaSteps: '登录 · 生成令牌 · 装 Agent · 导入 MCP',
    ctaLine: '一个 MCP，你的所有电脑。',
    machines: [
      {place: '家里', os: 'Windows', cmd: '家里 Windows'},
      {place: '公司', os: 'macOS', cmd: '公司 macOS'},
      {place: '机房', os: 'Linux', cmd: '机房 Linux'},
    ],
  },
  en: {
    painTitle: 'People connect. Computers do not.',
    home: 'HOME',
    office: 'WORK',
    colo: 'COLO',
    online: 'Online',
    offline: 'Dropped',
    official: 'OFFICIAL REMOTE',
    connecting: 'Connecting to your machines…',
    disconnected: 'Connection lost',
    stamp: 'Official channel · dropped again',
    productTitle: 'One tool. Every computer. Anywhere.',
    sameCmd: 'One command · all three receive it',
    principleTitle: 'Tool → cloud hub → every PC',
    toolKicker: 'TOOL',
    toolTitle: 'Cursor / Claude',
    toolSub: 'Any interactive AI · MCP',
    hubKicker: 'SERVER',
    hubTitle: 'fleet.ginfo.cc',
    hubSub: 'Cloud hub · outbound only',
    winSub: 'Agent dials out',
    linuxSub: 'Agent dials out',
    macSub: 'Agent dials out',
    principleCaption: 'Devices only dial out · no inbound ports · any arch',
    collabTitle: 'Switch the client. The fleet stays.',
    mcpImported: 'MCP loaded',
    sameCreds: '  · same URL + token',
    officialCh: 'OFFICIAL',
    officialDown: 'Dropped',
    officialSub: 'Session gone. Machines leave the chat.',
    fleetOn: 'Still on',
    fleetSub: 'Bound to the hub, not one vendor client.',
    setupTitle: 'Four values. Then every PC is reachable.',
    key1t: 'Domain URL',
    key1s: 'https://fleet.ginfo.cc',
    key2t: 'Hub token',
    key2s: 'Mint flt_… in Settings',
    key3t: 'Agent on each PC',
    key3s: 'Windows / Linux / macOS',
    key4t: 'Import the tool',
    key4s: 'Any interactive AI · MCP',
    cloudTitle: 'Local is a CLI. Cloud is the product.',
    localKicker: 'LOCAL  your own machine',
    localTitle: 'At most a CLI',
    localBody: 'A hub on localhost cannot run a fleet. Other OS cannot join. Nowhere near “from anywhere.”',
    cloudKicker: 'CLOUD  fleet.ginfo.cc',
    cloudHead: 'This is the product',
    cloudBody: 'Put the server in the cloud. Windows, Linux, Mac dial out. One tool reaches every PC.',
    ctaKicker: 'Try it first',
    ctaUrl: 'fleet.ginfo.cc',
    ctaSteps: 'Log in · mint a token · install Agent · import MCP',
    ctaLine: 'One MCP. All your computers.',
    machines: [
      {place: 'HOME', os: 'Windows', cmd: 'Home Windows'},
      {place: 'WORK', os: 'macOS', cmd: 'Work macOS'},
      {place: 'COLO', os: 'Linux', cmd: 'Colo Linux'},
    ],
  },
} as const;

export type Copy = (typeof COPY)[Locale];
